# Generated by Django 5.2.7 on 2026-09-13 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="ISBN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "format",
                    models.CharField(
                        choices=[("10", "ISBN-10"), ("13", "ISBN-13")],
                        default="13",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "ISBN",
                "verbose_name_plural": "ISBNs",
                "db_table": "isbns",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Reseña",
                "verbose_name_plural": "Reseñas",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "openlibrary_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("biography", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "db_table": "authors",
                "indexes": [
                    models.Index(fields=["name"], name="authors_name_e12c66_idx"),
                    models.Index(
                        fields=["openlibrary_id"], name="authors_openlib_0c788a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openlibrary_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("publish_date", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("number_of_pages", models.IntegerField(blank=True, null=True)),
                ("cover_url", models.URLField(blank=True)),
                ("stock", models.IntegerField(default=0)),
                ("available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="books.author"),
                ),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
                "db_table": "books",
            },
        ),
        migrations.CreateModel(
            name="BookStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("physical_id", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("borrowed", "Prestado"),
                            ("maintenance", "En Mantenimiento"),
                            ("lost", "Perdido"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("condition", models.CharField(default="good", max_length=20)),
                ("added_date", models.DateField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock de Libro",
                "verbose_name_plural": "Stocks de Libros",
                "db_table": "book_stocks",
            },
        ),
    ]
