# Generated by Django 5.2.7 on 2026-09-13 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(related_name="libros", to="books.category"),
        ),
        migrations.AddField(
            model_name="isbn",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isbns",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="books_title_7a737c_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["-created_at"], name="books_created_9e859d_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["available", "stock"], name="books_availab_41bdea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "book")},
        ),
    ]
