# Generated by Django 5.2.7 on 2025-10-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='openlibrary_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
