# Generated by Django 5.2.7 on 2026-10-08 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBookStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_read", "Quiero leer"),
                            ("reading", "Leyendo"),
                            ("read", "Leído"),
                        ],
                        db_index=True,
                        default="to_read",
                        max_length=10,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("finished_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_statuses",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de lectura",
                "verbose_name_plural": "Estados de lectura",
                "db_table": "user_book_statuses",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="user_book_s_user_id_02d6da_idx"
                    ),
                    models.Index(
                        fields=["book", "status"], name="user_book_s_book_id_8193f4_idx"
                    ),
                ],
                "unique_together": {("user", "book")},
            },
        ),
    ]
