# Generated by Django 5.2.7 on 2026-09-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="books.isbn"
            ),
        ),
    ]
