# Generated by Django 5.2.7 on 2026-09-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="authors", to="books.author"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.ManyToManyField(
                blank=True, related_name="isbns", to="books.isbn"
            ),
        ),
    ]
