# Generated by Django 5.2.7 on 2026-09-01 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_openlibrary_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(db_index=True, max_length=20, unique=True)),
                ('format', models.CharField(choices=[('10', 'ISBN-10'), ('13', 'ISBN-13')], default='13', max_length=10)),
            ],
            options={
                'verbose_name': 'ISBN',
                'verbose_name_plural': 'ISBNs',
                'db_table': 'isbns',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='openlibrary_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('openlibrary_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'authors',
                'indexes': [models.Index(fields=['name'], name='authors_name_e12c66_idx'), models.Index(fields=['openlibrary_id'], name='authors_openlib_0c788a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_title_7a737c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='books_created_9e859d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['available', 'stock'], name='books_availab_41bdea_idx'),
        ),
        migrations.AddField(
            model_name='isbn',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbns', to='books.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.author'),
        ),
    ]
