# Generated by Django 5.2.7 on 2026-09-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_authors_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="books.author"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(related_name="books", to="books.category"),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="books.isbn"
            ),
        ),
    ]
