# Generated by Django 5.2.7 on 2026-10-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CulturalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("taller", "Taller"),
                            ("charla", "Charla"),
                            ("lectura", "Club de lectura"),
                            ("presentacion", "Presentación de libro"),
                            ("exposicion", "Exposición"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Tipo de evento",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                ("start_time", models.TimeField(verbose_name="Hora de inicio")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de finalización"
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Lugar")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cupo máximo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("realizado", "Realizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="programado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evento cultural",
                "verbose_name_plural": "Eventos culturales",
                "db_table": "cultural_events",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
