# Generated by Django 5.2.7 on 2026-10-08 00:33

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                choices=[
                    ("images/Armibiblio-.png", "Tato el tatú carreta"),
                    ("images/Bentevíbiblio-.png", "Benteví el benteveo"),
                    ("images/Carpibiblio-.png", "Carpi el carpincho"),
                    ("images/Doctorbiblio-.png", "Doc el tordo"),
                    ("images/DonBargresbiblio-.png", "Don Borges el bagre"),
                    ("images/Francabiblio-.png", "Franca la Ballena Austral"),
                    ("images/Guanabiblio-.png", "Tato el guanaco"),
                    ("images/Guaribiblio-.png", "Wari el aguará guazú"),
                    ("images/Hormibiblio-.png", "Hormi el oso hormiguero"),
                    ("images/Hornebiblio-.png", "Jero el hornero"),
                    ("images/Jaguabiblio-.png", "Yasí el yaguareté"),
                    ("images/Llamibiblio-.png", "Tuy la llama"),
                    ("images/Parribiblio-.png", "Rolo el loro"),
                    ("images/Pingubiblio-.png", "Pingu la pingüina"),
                    ("images/Susibiblio-.png", "Zazo el zorro"),
                    ("images/Tortubiblio-.png", "Tuga la tortuga"),
                ],
                default=apps.users.models.random_avatar,
                null=True,
                upload_to="",
            ),
        ),
    ]
