# Generated by Django 5.2.7 on 2026-09-13 02:43

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                choices=[
                    ("images/Armibiblio-.svg", "Tato el tatú carreta"),
                    ("images/Bentevíbiblio-.svg", "Benteví el benteveo"),
                    ("images/Carpibiblio-.svg", "Carpi el carpincho"),
                    ("images/Doctorbiblio-.svg", "Doctor el tordo"),
                    ("images/DonBargresbiblio-.svg", "Don Bargres el bagre"),
                    ("images/Francabiblio-.svg", "Franca la Ballena Austral"),
                    ("images/Guanabiblio-.svg", "Guana el guanaco"),
                    ("images/Guaribiblio-.svg", "Guari el aguará guazú"),
                    ("images/Hormibiblio-.svg", "Hormi el oso hormiguero"),
                    ("images/Hornebiblio-.svg", "Horne el hornero"),
                    ("images/Jaguabiblio-.svg", "Yasí el yaguareté"),
                    ("images/Llamibiblio-.svg", "Llami la llama"),
                    ("images/Parribiblio-.svg", "Parri el loro"),
                    ("images/Pingubiblio-.svg", "Pingu la pingüina"),
                    ("images/Susibiblio-.svg", "Zazo el zorro"),
                    ("images/Tortubiblio-.svg", "Tuga la tortuga"),
                ],
                default=apps.users.models.random_avatar,
                null=True,
                upload_to="",
            ),
        ),
    ]
