# Generated by Django 5.2.7 on 2025-10-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_openlibrary_id'),
        ('users', '0002_remove_userprofile_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
