# Generated by Django 5.2.7 on 2026-09-01 19:58

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_favorite_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(help_text='Formato: 12345678 o 12.345.678', max_length=20, unique=True, validators=[apps.users.validators.validate_dni]),
        ),
    ]
