# Generated by Django 5.2.7 on 2026-09-13 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal (15 días)"),
                            ("express", "Express (3 días)"),
                            ("summer", "Verano (2 meses)"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Solicitud de Préstamo",
                "verbose_name_plural": "Solicitudes de Préstamo",
                "db_table": "loan_requests",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="Renewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("renewal_date", models.DateField(auto_now_add=True)),
                ("previous_due_date", models.DateField()),
                ("new_due_date", models.DateField()),
            ],
            options={
                "verbose_name": "Renovación",
                "verbose_name_plural": "Renovaciones",
                "db_table": "renewals",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal (15 días)"),
                            ("express", "Express (3 días)"),
                            ("summer", "Verano (2 meses)"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("loan_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("returned", "Devuelto"),
                            ("overdue", "Vencido"),
                            ("lost", "Perdido"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("renewal_count", models.IntegerField(default=0)),
                ("max_renewals", models.IntegerField(default=2)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
                "db_table": "loans",
            },
        ),
    ]
