# Generated by Django 5.2.7 on 2025-10-19 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('normal', 'Normal (15 días)'), ('express', 'Express (3 días)'), ('summer', 'Verano (2 meses)')], default='normal', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Préstamo',
                'verbose_name_plural': 'Solicitudes de Préstamo',
                'db_table': 'loan_requests',
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField(auto_now_add=True)),
                ('previous_due_date', models.DateField()),
                ('new_due_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Renovación',
                'verbose_name_plural': 'Renovaciones',
                'db_table': 'renewals',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('normal', 'Normal (15 días)'), ('express', 'Express (3 días)'), ('summer', 'Verano (2 meses)')], default='normal', max_length=10)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('renewed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('returned', 'Devuelto'), ('overdue', 'Vencido'), ('lost', 'Perdido')], max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'loans',
            },
        ),
    ]
