# Generated by Django 5.2.7 on 2026-09-13 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0002_initial"),
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_loan_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.book"
            ),
        ),
        migrations.AddField(
            model_name="loanrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="renewal",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="loans.loan"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["user", "status"], name="loans_user_id_efac20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["status", "-due_date"], name="loans_status_0c0fc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["return_date"], name="loans_return__9e5f6b_idx"),
        ),
        migrations.AddIndex(
            model_name="loanrequest",
            index=models.Index(
                fields=["user", "status"], name="loan_reques_user_id_3a8ebd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loanrequest",
            index=models.Index(
                fields=["status", "-request_date"], name="loan_reques_status_179df1_idx"
            ),
        ),
    ]
