# Generated by Django 5.2.7 on 2025-10-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='loan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('returned', 'Devuelto')], default='pending', max_length=20),
        ),
    ]
