# Generated by Django 5.2.7 on 2026-09-01 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_isbn_remove_book_isbn_book_description_and_more'),
        ('loans', '0003_loanrequest_loan_date_loanrequest_return_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'Solicitud de Préstamo', 'verbose_name_plural': 'Solicitudes de Préstamo'},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='renewed',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='loan_date',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='return_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='max_renewals',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='loan',
            name='renewal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.book'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('returned', 'Devuelto'), ('overdue', 'Vencido'), ('lost', 'Perdido')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loan_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status'], name='loans_user_id_efac20_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', '-due_date'], name='loans_status_0c0fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['return_date'], name='loans_return__9e5f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['user', 'status'], name='loan_reques_user_id_3a8ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['status', '-request_date'], name='loan_reques_status_179df1_idx'),
        ),
    ]
